### ISSUE TITLE
期間が異なる複数のライキングへの対応

### ISSUE THREAD

**Issue by megane9988** [m-g-n/mgn-ga-ranking#5]
例
- 全期間、30日間、1日などで期間をわけてランキングを表示させる

現在出来ていること
- カテゴリーごとのランキグなど、クエリーに対するフィルターで絞り込めるもの

**Comment by Shizumi** [comment]
それぞれの期間ごとに情報を取得する必要があるので、情報の保持のさせ方含め検討します。

**Comment by megane9988** [comment]
@Shizumi 
これは追加仕様なので。将来的な実装でもOKです！

**Comment by megane9988** [comment]
@Shizumi  こちらの優先度があげになります！

**Comment by Shizumi** [comment]
@megane9988 
承知しました
今週中（すみません稼働が水曜日までになります）に完了できるよう調整します。

**Comment by Shizumi** [comment]
@megane9988 
期間指定を自由に複数設定した場合の呼び出し方がうまくまとまらないので、一旦
- 1日
- 1週間
- 1ヶ月(30日)
での情報を事前に取得しておき、`mgnga_ranking_id()`に値を渡して自由に取得できるという仕様でいかがでしょうか？
渡せる値としては
- day
- week
- month
- custom (管理画面で指定した期間・現状出力されているもの)
を想定しています。

**Comment by megane9988** [comment]
@Shizumi  たすかります！
いい感じです！

**Comment by Shizumi** [comment]
ではこちらで進めます！

**Comment by Shizumi** [comment]
@megane9988 
作ってみました！

上記仕様どおり、`mgnga_ranking_id()` に値を渡してあげてください。
値が正しくない場合はcustomが走るようになっております。（未設定初期値もcustomです）

**Comment by megane9988** [comment]
ありがとうございます！
