### ISSUE TITLE
現在有効化出来ない

### ISSUE THREAD

**Issue by megane9988** [m-g-n/mgn-ga-ranking#6]
zipでDLして有効化すると、エラーが出て動かなそうです。ご確認くださいませ

( ! ) Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /Users/mgn_megane/Local Sites/clicccarnew/app/public/wp-content/plugins/mgn-ga-ranking/vendor/guzzlehttp/guzzle/src/functions.php on line 61

( ! ) Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /Users/mgn_megane/Local Sites/clicccarnew/app/public/wp-content/plugins/mgn-ga-ranking/vendor/guzzlehttp/guzzle/src/functions.php on line 61

( ! ) Notice: is_embed が<strong>誤って</strong>呼び出されました。条件付きクエリータグは、クエリーが実行される前には機能しません。それ以前では、常に false を返します。 詳しくは <a href="https://ja.wordpress.org/support/article/debugging-in-wordpress/">WordPress のデバッグ</a>をご覧ください。 (このメッセージはバージョン 3.1.0 で追加されました) in /Users/mgn_megane/Local Sites/clicccarnew/app/public/wp-includes/functions.php on line 5313

**Comment by Shizumi** [comment]
@megane9988 
私の手元の環境で複数試したのですが同様のエラーは発生しませんでした。
環境等可能な範囲で教えていただけることはできますか？

**Comment by megane9988** [comment]
@Shizumi 

もう少し調べたところ
https://github.com/humanmade/S3-Uploads

このプラグインと一緒に使うとうまく動かないということのようです。
ご確認くださいませ

```
 Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler()
in /Users/mgn_megane/Local Sites/clicccarnew/app/public/wp-content/plugins/mgn-ga-ranking-master_/vendor/guzzlehttp/guzzle/src/functions.php on line 61

コールスタック:

GuzzleHttp\choose_handler()
wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/HandlerStack.php:42
GuzzleHttp\HandlerStack::create()
wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Client.php:66
GuzzleHttp\Client::__construct()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php:26
Aws\H\G\GuzzleHandler::__construct()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/functions.php:279
Aws\default_http_handler()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/ClientResolver.php:634
Aws\ClientResolver::_default_handler()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/ClientResolver.php:288
Aws\ClientResolver::resolve()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/AwsClient.php:195
Aws\AwsClient::__construct()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/S3/S3Client.php:327
Aws\S3\S3Client::__construct()
wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/AwsClient.php:440
Aws\AwsClient::factory()
wp-content/plugins/s3-uploads/inc/class-s3-uploads.php:198
S3_Uploads::s3()
wp-content/plugins/s3-uploads/inc/class-s3-uploads.php:76
S3_Uploads::register_stream_wrapper()
wp-content/plugins/s3-uploads/inc/class-s3-uploads.php:46
S3_Uploads::setup()
wp-content/plugins/s3-uploads/s3-uploads.php:45
s3_uploads_init()
wp-includes/class-wp-hook.php:292
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:316
WP_Hook::do_action()
wp-includes/plugin.php:484
do_action()
wp-settings.php:423
require_once()
wp-config.php:93
require_once()
wp-load.php:37
require_once()
wp-admin/admin.php:34
require_once()
wp-admin/plugins.php:10
```

**Comment by Shizumi** [comment]
ありがとうございます。
それぞれcomposerを使用した別プラグインで競合しているようですね…
解決策を調べます。

**Comment by Shizumi** [comment]
@megane9988 
ログを見る感じS3-Uploadからmgn-ga-rankingのvenderにアクセスしようとしているようです。
S3-Uploadの方にvenderというディレクトリはありますでしょうか？

試しにcloneして、`composer install`前にS3-Uploadを有効化してmgn-ga-rankingを導入すると同様のエラーが発生したのでご確認ください。

**Comment by megane9988** [comment]
@Shizumi  venderありますね。
こういうときってどうするのがいいんでしょうね。

おそらくcomposerで使っているライブラリが、プラグインごとに重複していて、それがエラーにになってるってことですよね。

**Comment by Shizumi** [comment]
私の環境だと、
S3にvendorがある→エラー起きない
vendorが無い→何故かこっちのvendorを見に来てエラーが発生
なんですよね…
ご迷惑おかけして申し訳ありませんがもう少し調べさせてください

**Comment by megane9988** [comment]
@Shizumi  なるほど、ちょっと試してみます！

**Comment by megane9988** [comment]
他プラグインで利用しているcomposer内のバージョン違いによるバッティングということでclose
